# Generated by Django 3.2.6 on 2021-09-07 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Трансмиссионное масло', 'Трансмиссионное масло'), ('Масло для строительной техники', 'Масло для строительной техники'), ('Компрессорное масло', 'Компрессорное масло'), ('Моторное масло', 'Моторное масло'), ('Масло для мототехники', 'Масло для мототехники')], max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название товара')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='noimage.png', upload_to='no_image', verbose_name='Изображение')),
                ('availability', models.BooleanField(default=True)),
                ('approvals_certificates', models.CharField(blank=True, max_length=255, verbose_name='Допуски, сертификаты')),
                ('density_at_20_C', models.CharField(blank=True, max_length=50, verbose_name='Плотность при 20°С')),
                ('viscosity_at_40_C', models.CharField(blank=True, max_length=50, verbose_name='Вязкость при 40°С')),
                ('viscosity_at_100_C', models.CharField(blank=True, max_length=50, verbose_name='Вязкость при 100°С')),
                ('viscosity_at_minus_26_C', models.CharField(blank=True, max_length=50, verbose_name='Вязкость при -26°С')),
                ('viscosity_at_minus_30_C', models.CharField(blank=True, max_length=50, verbose_name='Вязкость при -30°С')),
                ('viscosity_index', models.CharField(blank=True, max_length=50, verbose_name='Индекс вязкости')),
                ('flash_point', models.CharField(blank=True, max_length=50, verbose_name='Точка возгорания')),
                ('pour_point', models.CharField(blank=True, max_length=50, verbose_name='Температура застывания')),
                ('maximum_pumping_temp', models.CharField(blank=True, max_length=50, verbose_name='Предельная температура перекачиваемости')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена (грн.)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': ('Корзина',),
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
