# Generated by Django 3.2.6 on 2021-09-02 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionOils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название товара')),
                ('text', models.TextField(null=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('approvals_certificates', models.CharField(max_length=255, null=True, verbose_name='Допуски, сертификаты')),
                ('density_at_20_C', models.CharField(max_length=50, null=True, verbose_name='Плотность при 20°С')),
                ('viscosity_at_40_C', models.CharField(max_length=50, null=True, verbose_name='Вязкость при 40°С')),
                ('viscosity_at_100_C', models.CharField(max_length=50, null=True, verbose_name='Вязкость при 100°С')),
                ('viscosity_at_minus_30_C', models.CharField(max_length=50, null=True, verbose_name='Вязкость при -30°С')),
                ('viscosity_index', models.CharField(max_length=50, null=True, verbose_name='Индекс вязкости')),
                ('flash_point', models.CharField(max_length=50, null=True, verbose_name='Точка возгорания')),
                ('pour_point', models.CharField(max_length=50, null=True, verbose_name='Температура застывания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorOilsForCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название товара')),
                ('text', models.TextField(null=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('density_at_20_C', models.CharField(max_length=50, null=True, verbose_name='Плотность при 20°С')),
                ('viscosity_at_40_C', models.CharField(max_length=50, null=True, verbose_name='Вязкость при 40°С')),
                ('viscosity_at_100_C', models.CharField(max_length=50, null=True, verbose_name='Вязкость при 100°С')),
                ('viscosity_at_minus_30_C', models.CharField(max_length=50, null=True, verbose_name='Вязкость при -30°С')),
                ('viscosity_index', models.CharField(max_length=50, null=True, verbose_name='Индекс вязкости')),
                ('flash_point', models.CharField(max_length=50, null=True, verbose_name='Точка возгорания')),
                ('pour_point', models.CharField(max_length=50, null=True, verbose_name='Температура застывания')),
                ('maximum_pumping_temp', models.CharField(max_length=50, null=True, verbose_name='Предельная температура перекачиваемости')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='third_app.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='third_app.CartProduct'),
        ),
    ]
