# Generated by Django 3.2.6 on 2021-09-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Масло для строительной техники', 'Масло для строительной техники'), ('Масло для мототехники', 'Масло для мототехники'), ('Трансмиссионное масло', 'Трансмиссионное масло'), ('Моторное масло', 'Моторное масло'), ('Компрессорное масло', 'Компрессорное масло')], max_length=255, verbose_name='Название категории'),
        ),
    ]
