# Generated by Django 3.2.6 on 2021-09-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': ('Корзина',), 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='motoroilsforcars',
            options={'verbose_name': 'Моторное масло для легковых авто', 'verbose_name_plural': 'Моторные масла для легковых авто'},
        ),
        migrations.AlterModelOptions(
            name='transmissionoils',
            options={'verbose_name': 'Трансмиссионное масло', 'verbose_name_plural': 'Трансмиссионные масла'},
        ),
    ]
