# Generated by Django 3.2.6 on 2021-09-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Компрессорное масло', 'Компрессорное масло'), ('Трансмиссионное масло', 'Трансмиссионное масло'), ('Масло для строительной техники', 'Масло для строительной техники'), ('Масло для мототехники', 'Масло для мототехники'), ('Моторное масло', 'Моторное масло')], max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название товара'),
        ),
    ]
