# Generated by Django 3.2.6 on 2021-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0003_auto_20210908_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Моторное масло', 'Моторное масло'), ('Масло для мототехники', 'Масло для мототехники'), ('Масло для строительной техники', 'Масло для строительной техники'), ('Компрессорное масло', 'Компрессорное масло'), ('Трансмиссионное масло', 'Трансмиссионное масло')], max_length=255, verbose_name='Название категории'),
        ),
    ]
