# Generated by Django 3.2.6 on 2021-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар(ов)'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Компрессорное масло', 'Компрессорное масло'), ('Масло для строительной техники', 'Масло для строительной техники'), ('Моторное масло', 'Моторное масло'), ('Трансмиссионное масло', 'Трансмиссионное масло'), ('Масло для мототехники', 'Масло для мототехники')], max_length=255, verbose_name='Название категории'),
        ),
    ]
