# Generated by Django 3.2.6 on 2021-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0009_auto_20210916_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': '* Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '* Все товары'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Трансмиссионное масло', 'Трансмиссионное масло'), ('Масло для мототехники', 'Масло для мототехники'), ('Компрессорное масло', 'Компрессорное масло'), ('Масло для строительной техники', 'Масло для строительной техники'), ('Моторное масло', 'Моторное масло')], max_length=255, verbose_name='Название категории'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
