# Generated by Django 3.2.6 on 2021-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0010_auto_20210916_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Масло для строительной техники', 'Масло для строительной техники'), ('Компрессорное масло', 'Компрессорное масло'), ('Моторное масло', 'Моторное масло'), ('Масло для мототехники', 'Масло для мототехники'), ('Трансмиссионное масло', 'Трансмиссионное масло')], max_length=255, verbose_name='Название категории'),
        ),
    ]
